<?php
require_once __DIR__ . '/../../includes/auth.php';
require_once __DIR__ . '/../../includes/database.php';
require_once __DIR__ . '/QPGenerator.php';

Auth::requireRole('admin', 'principal');

$paperId = (int)($_GET['id'] ?? 0);
if (!$paperId) { header('Location: generate.php'); exit; }

$db = Database::getInstance();
$paper = $db->fetchOne(
    "SELECT qp.*, s.subject_name, s.subject_code, s.semester,
            d.name as dept_name, d.code as dept_code,
            u.full_name as generated_by_name,
            a.full_name as approved_by_name,
            t.template_name
     FROM question_papers qp
     JOIN subjects s ON qp.subject_id=s.id
     JOIN departments d ON s.department_id=d.id
     JOIN users u ON qp.generated_by=u.id
     LEFT JOIN users a ON qp.approved_by=a.id
     JOIN qp_templates t ON qp.template_id=t.id
     WHERE qp.id=?",
    [$paperId]
);

if (!$paper) { echo 'Paper not found.'; exit; }

$data = json_decode($paper['paper_data'], true);

// Handle approval
if (isset($_GET['action']) && $_GET['action'] === 'approve') {
    $db->update('question_papers', ['status'=>'approved','approved_by'=>$_SESSION['user_id']], 'id=?', [$paperId]);
    Auth::logActivity($_SESSION['user_id'], 'APPROVE_QP', 'question_papers', "Approved paper #$paperId");
    header('Location: view.php?id='.$paperId.'&msg=approved');
    exit;
}

$pageTitle = 'View Paper – ' . $paper['paper_code'];
require_once __DIR__ . '/../../includes/layout.php';
?>

<?php if (isset($_GET['msg']) && $_GET['msg']==='approved'): ?>
<div class="flash-msg flash-success"><i class="fas fa-check-circle"></i> Paper approved successfully!</div>
<?php endif; ?>

<!-- Action bar -->
<div style="display:flex;gap:12px;flex-wrap:wrap;margin-bottom:24px;">
  <a href="generate.php" class="btn btn-outline"><i class="fas fa-arrow-left"></i> Back</a>
  <a href="print.php?id=<?= $paperId ?>" class="btn btn-primary" target="_blank"><i class="fas fa-print"></i> Print Paper</a>
  <?php if ($paper['status'] === 'pending_approval' || $paper['status'] === 'draft'): ?>
  <a href="?id=<?= $paperId ?>&action=approve" class="btn btn-primary" style="background:#10b981;" onclick="return confirm('Approve this paper?')">
    <i class="fas fa-check-circle"></i> Approve Paper
  </a>
  <?php endif; ?>
  <span class="badge <?php $sm=['draft'=>'warning','pending_approval'=>'info','approved'=>'success','printed'=>'purple']; echo 'badge-'.($sm[$paper['status']]??'info'); ?>" style="font-size:13px;padding:8px 16px;">
    <?= ucfirst(str_replace('_',' ',$paper['status'])) ?>
  </span>
</div>

<!-- Paper meta -->
<div class="card" style="margin-bottom:24px;">
  <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:16px;">
    <div>
      <div style="font-size:11px;color:#94a3b8;text-transform:uppercase;letter-spacing:1px;">Paper Code</div>
      <div style="font-weight:700;font-family:monospace;font-size:15px;"><?= htmlspecialchars($paper['paper_code']) ?></div>
    </div>
    <div>
      <div style="font-size:11px;color:#94a3b8;text-transform:uppercase;letter-spacing:1px;">Subject</div>
      <div style="font-weight:600;"><?= htmlspecialchars($paper['subject_code']) ?> – <?= htmlspecialchars($paper['subject_name']) ?></div>
    </div>
    <div>
      <div style="font-size:11px;color:#94a3b8;text-transform:uppercase;letter-spacing:1px;">Exam Type</div>
      <span class="badge badge-purple"><?= $paper['exam_type'] ?></span>
    </div>
    <div>
      <div style="font-size:11px;color:#94a3b8;text-transform:uppercase;letter-spacing:1px;">Marks / Duration</div>
      <div style="font-weight:600;"><?= $paper['total_marks'] ?> Marks / <?= $paper['duration_minutes']/60 ?> Hours</div>
    </div>
    <div>
      <div style="font-size:11px;color:#94a3b8;text-transform:uppercase;letter-spacing:1px;">Department</div>
      <span class="badge badge-info"><?= htmlspecialchars($paper['dept_name']) ?></span>
    </div>
    <div>
      <div style="font-size:11px;color:#94a3b8;text-transform:uppercase;letter-spacing:1px;">Semester</div>
      <div style="font-weight:600;"><?= $paper['semester'] ?></div>
    </div>
    <div>
      <div style="font-size:11px;color:#94a3b8;text-transform:uppercase;letter-spacing:1px;">Generated By</div>
      <div style="font-weight:600;"><?= htmlspecialchars($paper['generated_by_name']) ?></div>
    </div>
    <div>
      <div style="font-size:11px;color:#94a3b8;text-transform:uppercase;letter-spacing:1px;">Set</div>
      <div style="font-weight:700;font-size:18px;"><?= $data['set_number'] > 1 ? 'Set '.chr(64+$data['set_number']) : 'Set A' ?></div>
    </div>
  </div>
</div>

<!-- PAPER CONTENT PREVIEW -->
<div class="card">
  <div class="card-title"><i class="fas fa-file-lines"></i> Paper Preview</div>

  <?php foreach ($data['sections'] as $sIdx => $section): ?>
  <div style="margin-bottom:24px;">
    <div style="background:#1e293b;color:white;padding:10px 16px;border-radius:8px;margin-bottom:12px;display:flex;justify-content:space-between;align-items:center;">
      <span style="font-weight:700;font-family:var(--font-head);">
        PART <?= $section['section_label'] ?> – <?= htmlspecialchars($section['title']) ?>
      </span>
      <span style="font-size:12px;color:#94a3b8;"><?= count($section['questions']) ?> Questions × <?= $section['marks_per_q'] ?> Marks</span>
    </div>
    <div style="padding:4px 16px;background:#f8fafc;border-left:3px solid #e2e8f0;margin-bottom:12px;font-size:13px;color:#64748b;font-style:italic;">
      <?= htmlspecialchars($section['instruction']) ?>
    </div>

    <?php
    $qNum = ($sIdx * 10) + 1;
    $total = count($section['questions']);
    foreach ($section['questions'] as $idx => $q):
    ?>
    <div style="display:flex;gap:12px;padding:12px;margin-bottom:8px;border:1px solid #e2e8f0;border-radius:8px;background:white;<?= !empty($section['or_choice']) && $idx % 2 === 1 ? 'border-left:3px solid #f59e0b;' : '' ?>">
      <div style="min-width:30px;font-weight:700;color:#1e293b;">Q<?= $qNum++ ?>.</div>
      <div style="flex:1;">
        <div style="line-height:1.7;color:#334155;"><?= nl2br(htmlspecialchars($q['question_text'])) ?></div>
        <div style="display:flex;gap:6px;margin-top:8px;flex-wrap:wrap;">
          <span class="badge badge-purple" style="font-size:10px;"><?= htmlspecialchars($q['co_code']) ?></span>
          <span class="badge badge-info" style="font-size:10px;"><?= htmlspecialchars($q['bloom_level']) ?></span>
          <span class="badge badge-warning" style="font-size:10px;"><?= ucfirst($q['difficulty']) ?></span>
          <?php if ($q['diagram_required']): ?><span class="badge badge-success" style="font-size:10px;">Diagram</span><?php endif; ?>
        </div>
      </div>
      <div style="min-width:60px;text-align:right;">
        <span style="background:#1e293b;color:white;padding:4px 10px;border-radius:6px;font-weight:700;font-size:13px;">[<?= $q['marks'] ?>M]</span>
      </div>
    </div>
    <?php if (!empty($section['or_choice']) && $idx % 2 === 0 && $idx < $total - 1): ?>
    <div style="text-align:center;font-weight:700;color:#f59e0b;font-size:14px;letter-spacing:4px;margin:4px 0;">—— OR ——</div>
    <?php endif; ?>
    <?php endforeach; ?>
  </div>
  <?php endforeach; ?>

  <!-- CO-PO Table -->
  <?php if (!empty($data['co_po_summary'])): ?>
  <div style="margin-top:16px;padding-top:16px;border-top:2px solid #e2e8f0;">
    <div style="font-weight:700;margin-bottom:10px;font-family:var(--font-head);">CO-PO Attainment Mapping</div>
    <div style="overflow-x:auto;">
      <table style="border-collapse:collapse;font-size:13px;">
        <tr>
          <th style="border:1px solid #e2e8f0;padding:6px 12px;background:#f8fafc;">CO / PO</th>
          <?php
          $poKeys = [];
          foreach ($data['co_po_summary'] as $co => $pos) { foreach ($pos as $po => $l) $poKeys[] = $po; }
          $poKeys = array_unique($poKeys); sort($poKeys);
          foreach ($poKeys as $po): ?>
          <th style="border:1px solid #e2e8f0;padding:6px 12px;background:#f8fafc;"><?= htmlspecialchars($po) ?></th>
          <?php endforeach; ?>
        </tr>
        <?php foreach ($data['co_po_summary'] as $co => $pos): ?>
        <tr>
          <td style="border:1px solid #e2e8f0;padding:6px 12px;font-weight:700;"><?= htmlspecialchars($co) ?></td>
          <?php foreach ($poKeys as $po): ?>
          <td style="border:1px solid #e2e8f0;padding:6px 12px;text-align:center;">
            <?php $lvl = $pos[$po] ?? '-'; $lvlColor=['1'=>'#fef3c7','2'=>'#dbeafe','3'=>'#dcfce7'];?>
            <?php if ($lvl !== '-'): ?><span style="background:<?= $lvlColor[$lvl]??'#f1f5f9' ?>;padding:2px 8px;border-radius:4px;font-weight:700;"><?= $lvl ?></span><?php else: ?>—<?php endif; ?>
          </td>
          <?php endforeach; ?>
        </tr>
        <?php endforeach; ?>
      </table>
    </div>
    <div style="font-size:11px;color:#94a3b8;margin-top:6px;">1=Low, 2=Medium, 3=High attainment</div>
  </div>
  <?php endif; ?>
</div>

</div></div></body></html>
