<?php
require_once __DIR__ . '/../../includes/auth.php';
require_once __DIR__ . '/../../includes/database.php';

Auth::requireRole('principal');

$db = Database::getInstance();

$stats = [
    'hods'      => $db->fetchOne("SELECT COUNT(*) as c FROM users WHERE role='hod' AND is_active=1")['c'],
    'staff'     => $db->fetchOne("SELECT COUNT(*) as c FROM users WHERE role='staff' AND is_active=1")['c'],
    'questions' => $db->fetchOne("SELECT COUNT(*) as c FROM questions WHERE is_active=1")['c'],
    'papers'    => $db->fetchOne("SELECT COUNT(*) as c FROM question_papers")['c'],
    'pending'   => $db->fetchOne("SELECT COUNT(*) as c FROM question_papers WHERE status='pending_approval'")['c'],
    'subjects'  => $db->fetchOne("SELECT COUNT(*) as c FROM subjects WHERE is_active=1")['c'],
];

$pendingPapers = $db->fetchAll(
    "SELECT qp.*, s.subject_name, s.subject_code, d.name as dept_name, u.full_name as by_name
     FROM question_papers qp
     JOIN subjects s ON qp.subject_id=s.id
     JOIN departments d ON s.department_id=d.id
     JOIN users u ON qp.generated_by=u.id
     WHERE qp.status='pending_approval'
     ORDER BY qp.created_at DESC LIMIT 10"
);

$recentPapers = $db->fetchAll(
    "SELECT qp.*, s.subject_name, s.subject_code, d.code as dept_code, u.full_name as by_name
     FROM question_papers qp
     JOIN subjects s ON qp.subject_id=s.id
     JOIN departments d ON s.department_id=d.id
     JOIN users u ON qp.generated_by=u.id
     ORDER BY qp.created_at DESC LIMIT 6"
);

// Dept-wise paper counts
$deptStats = $db->fetchAll(
    "SELECT d.name, d.code, COUNT(qp.id) as paper_count
     FROM departments d
     LEFT JOIN subjects s ON s.department_id=d.id
     LEFT JOIN question_papers qp ON qp.subject_id=s.id
     GROUP BY d.id ORDER BY paper_count DESC"
);

$pageTitle = 'Principal Dashboard';
require_once __DIR__ . '/../../includes/layout.php';
?>

<!-- STATS -->
<div class="stats-grid">
  <?php
  $statItems = [
    ['label'=>'HODs',          'val'=>$stats['hods'],      'color'=>'#8b5cf6','bg'=>'#ede9fe','icon'=>'fa-chalkboard-user'],
    ['label'=>'Staff',         'val'=>$stats['staff'],     'color'=>'#10b981','bg'=>'#dcfce7','icon'=>'fa-person-chalkboard'],
    ['label'=>'Questions',     'val'=>$stats['questions'], 'color'=>'#1e40af','bg'=>'#dbeafe','icon'=>'fa-circle-question'],
    ['label'=>'Papers',        'val'=>$stats['papers'],    'color'=>'#d97706','bg'=>'#fef3c7','icon'=>'fa-file-alt'],
    ['label'=>'Pending Review','val'=>$stats['pending'],   'color'=>'#dc2626','bg'=>'#fee2e2','icon'=>'fa-clock'],
    ['label'=>'Subjects',      'val'=>$stats['subjects'],  'color'=>'#0369a1','bg'=>'#e0f2fe','icon'=>'fa-book'],
  ];
  foreach ($statItems as $s): ?>
  <div class="stat-card">
    <div class="stat-icon" style="background:<?= $s['bg'] ?>;color:<?= $s['color'] ?>;"><i class="fas <?= $s['icon'] ?>"></i></div>
    <div>
      <div class="stat-value" style="color:<?= $s['color'] ?>;"><?= $s['val'] ?></div>
      <div class="stat-label"><?= $s['label'] ?></div>
    </div>
  </div>
  <?php endforeach; ?>
</div>

<!-- QUICK ACTIONS -->
<div class="card" style="margin-bottom:24px;">
  <div class="card-title"><i class="fas fa-bolt"></i> Quick Actions</div>
  <div style="display:flex;flex-wrap:wrap;gap:12px;">
    <a href="../qp_generator/generate.php" class="btn btn-primary"><i class="fas fa-file-circle-plus"></i> Generate Paper</a>
    <a href="users.php?action=add&role=hod" class="btn btn-primary" style="background:#8b5cf6;"><i class="fas fa-user-plus"></i> Add HOD</a>
    <a href="users.php?action=add&role=staff" class="btn btn-primary" style="background:#10b981;"><i class="fas fa-user-plus"></i> Add Staff</a>
    <a href="approve.php" class="btn btn-primary" style="background:#ef4444;">
      <i class="fas fa-check-circle"></i> Approve Papers
      <?php if ($stats['pending'] > 0): ?><span style="background:white;color:#ef4444;border-radius:50%;padding:0 6px;font-size:11px;margin-left:4px;"><?= $stats['pending'] ?></span><?php endif; ?>
    </a>
    <a href="papers.php" class="btn btn-outline"><i class="fas fa-files"></i> All Papers</a>
    <a href="reports.php" class="btn btn-outline"><i class="fas fa-chart-bar"></i> Reports</a>
  </div>
</div>

<div style="display:grid;grid-template-columns:1fr 300px;gap:24px;align-items:start;">

  <!-- PENDING APPROVAL -->
  <?php if (!empty($pendingPapers)): ?>
  <div class="card">
    <div class="card-title" style="color:#dc2626;"><i class="fas fa-clock"></i> Papers Awaiting Approval (<?= count($pendingPapers) ?>)</div>
    <div class="table-wrap">
      <table>
        <thead><tr><th>Paper Code</th><th>Subject</th><th>Department</th><th>Type</th><th>Generated By</th><th>Date</th><th>Actions</th></tr></thead>
        <tbody>
          <?php foreach ($pendingPapers as $p): ?>
          <tr>
            <td><code style="font-size:11px;"><?= htmlspecialchars($p['paper_code']) ?></code></td>
            <td><?= htmlspecialchars($p['subject_code']) ?></td>
            <td><span class="badge badge-info"><?= htmlspecialchars($p['dept_name']) ?></span></td>
            <td><span class="badge badge-purple"><?= $p['exam_type'] ?></span></td>
            <td><?= htmlspecialchars($p['by_name']) ?></td>
            <td style="font-size:12px;"><?= date('d M y', strtotime($p['created_at'])) ?></td>
            <td>
              <a href="../qp_generator/view.php?id=<?= $p['id'] ?>" class="btn btn-outline btn-sm"><i class="fas fa-eye"></i></a>
              <a href="approve.php?approve=<?= $p['id'] ?>" class="btn btn-primary btn-sm" style="background:#10b981;"><i class="fas fa-check"></i></a>
              <a href="../qp_generator/print.php?id=<?= $p['id'] ?>" class="btn btn-outline btn-sm" target="_blank"><i class="fas fa-print"></i></a>
            </td>
          </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    </div>
  </div>
  <?php else: ?>
  <!-- Recent papers when no pending -->
  <div class="card">
    <div class="card-title"><i class="fas fa-file-alt"></i> Recent Papers</div>
    <div class="table-wrap">
      <table>
        <thead><tr><th>Code</th><th>Subject</th><th>Dept</th><th>Type</th><th>Status</th><th>Actions</th></tr></thead>
        <tbody>
          <?php foreach ($recentPapers as $p): ?>
          <tr>
            <td><code style="font-size:11px;"><?= htmlspecialchars($p['paper_code']) ?></code></td>
            <td><?= htmlspecialchars($p['subject_code']) ?></td>
            <td><span class="badge badge-info"><?= htmlspecialchars($p['dept_code']) ?></span></td>
            <td><span class="badge badge-purple"><?= $p['exam_type'] ?></span></td>
            <td><?php $sm=['draft'=>'warning','pending_approval'=>'info','approved'=>'success','printed'=>'purple']; ?>
              <span class="badge badge-<?= $sm[$p['status']]??'info' ?>"><?= ucfirst(str_replace('_',' ',$p['status'])) ?></span></td>
            <td>
              <a href="../qp_generator/view.php?id=<?= $p['id'] ?>" class="btn btn-outline btn-sm"><i class="fas fa-eye"></i></a>
              <a href="../qp_generator/print.php?id=<?= $p['id'] ?>" class="btn btn-outline btn-sm" target="_blank"><i class="fas fa-print"></i></a>
            </td>
          </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    </div>
  </div>
  <?php endif; ?>

  <!-- DEPT STATS -->
  <div class="card">
    <div class="card-title"><i class="fas fa-chart-bar"></i> Dept-wise Papers</div>
    <?php foreach ($deptStats as $ds): ?>
    <div style="margin-bottom:12px;">
      <div style="display:flex;justify-content:space-between;margin-bottom:4px;font-size:13px;">
        <span><?= htmlspecialchars($ds['code']) ?></span>
        <span style="font-weight:700;"><?= $ds['paper_count'] ?></span>
      </div>
      <div style="background:#f1f5f9;border-radius:99px;height:6px;overflow:hidden;">
        <?php $maxCount = max(array_column($deptStats, 'paper_count')) ?: 1; ?>
        <div style="background:var(--accent);height:100%;width:<?= round(($ds['paper_count']/$maxCount)*100) ?>%;border-radius:99px;transition:width 1s;"></div>
      </div>
    </div>
    <?php endforeach; ?>
  </div>

</div>

</div></div></body></html>
